[package]
name = "audio_core"
version = "0.1.0"
edition = "2024"

[dependencies]
symphonia = "0.5.4"
rodio = "0.21.1"
hound = "3.5"
serde = { version = "1.0", features = ["derive"] }
rustfft = "6.4.0"
lazy_static = "1.5.0"
